#-------------------------------------------------------------------------------
# Figure 2 (compact version): Forecasted functional changes
#
#   3 x 3 grid:

#                   Change in functional uniqueness
#     - columns : Locomotion / Diet / Reproduction
#     - within each panel: IUCN 100 (left) | IUCN AT (right) side by side
#
#   Sign conventions:
#     - Species change  : negative (species loss)
#     - FRic change     : negative (functional richness loss)
#     - FUn change      : positive if gain (surviving species more isolated)
#
#   Empirical  : coloured boxplot (stochastic) or horizontal line (deterministic)
#   Null       : grey violin
#   Annotation : SES + p-value (except Species change: no SES by construction)
#
# Depends on extinction_results generated by 02_ANALYSE_ExtinctionScenario.R
# (with $ses_stats per dimension).
#
# Author : A. Toussaint
#-------------------------------------------------------------------------------


# ============================================================================
# 0. Packages -----------------------------------------------------------------
# ============================================================================
required_pkgs <- c("ggplot2", "dplyr", "tidyr", "tibble", "patchwork")
to_install <- setdiff(required_pkgs, rownames(installed.packages()))
if (length(to_install) > 0) install.packages(to_install)
invisible(lapply(required_pkgs, library, character.only = TRUE))


# ============================================================================
# 1. Parameters ---------------------------------------------------------------
# ============================================================================
PARAMS_FIG <- list(
  results_path  = "data/processed/extinction_scenarios_results.rds",
  
  out_dir       = "figures",
  fig_basename  = "Fig2_forecasted_changes",
  width_mm      = 180,
  height_mm     = 150,
  dpi           = 600,
  
  base_font_size  = 9,
  dim_colors      = c(locomotion   = "#2E7D32",   # vert
                      diet         = "#C62828",   # rouge
                      reproduction = "#1565C0"),  # bleu
  null_fill       = "grey85",
  null_border     = "grey45",
  pval_text_size  = 2.4,
  
  dim_order      = c("locomotion", "diet", "reproduction"),
  dim_labels     = c(locomotion   = "Locomotion",
                     diet         = "Diet",
                     reproduction = "Reproduction"),
  scenario_order = c("IUCN 100", "IUCN AT"),
  
  # Labels et codes internes pour chaque ligne
  metric_codes   = c("species", "fric", "fun"),
  metric_labels  = c(species = "Species change (%)",
                     fric    = "FRic change (%)",
                     fun     = "FUn change (%)"),
  
  # Position of both scenarios on the X axis
  x_pos          = c("IUCN 100" = 1, "IUCN AT" = 2)
)
dir.create(PARAMS_FIG$out_dir, showWarnings = FALSE, recursive = TRUE)


# ============================================================================
# 2. Load and compute series -------- -----------------------------------------
# ============================================================================
extinction_results <- readRDS(PARAMS_FIG$results_path)

# n_sp_total needed for Species change as %.
n_sp_total <- if (exists("species_df")) {
  nrow(species_df)
} else if (!is.null(extinction_results[[1]]$n_species_total)) {
  extinction_results[[1]]$n_species_total
} else {
  warning("species_df introuvable. Veuillez assigner n_sp_total manuellement.")
  NA_integer_
}

# Build long table: empirical + null
build_long_df <- function(extinction_results, n_sp_total) {
  
  rows <- list()
  
  for (d in names(extinction_results)) {
    df <- extinction_results[[d]]$iter_df
    
    # --- Species change: negative convention for loss ---
    sp_emp_100  <- -100 * df$n_extinct_100 / n_sp_total
    sp_emp_AT   <- -100 * df$n_extinct_AT  / n_sp_total
    # Null = empirical for Species change (same n extinctions by construction).
    # Le violin sera donc visuellement aplati = pas de signal de SES, c'est OK.
    sp_null_100 <- sp_emp_100
    sp_null_AT  <- sp_emp_AT
    
    # --- FRic change: negative convention for loss ---
    fric_emp_100  <- -100 * df$loss_FRic_100
    fric_emp_AT   <- -100 * df$loss_FRic_AT
    fric_null_100 <- -100 * df$loss_FRic_rand_100
    fric_null_AT  <- -100 * df$loss_FRic_rand_AT
    
    # --- FUn change: raw sign (gain = positive, loss = negative) ---
    fun_emp_100   <- 100 * df$delta_FUn_100
    fun_emp_AT    <- 100 * df$delta_FUn_AT
    fun_null_100  <- 100 * df$delta_FUn_rand_100
    fun_null_AT   <- 100 * df$delta_FUn_rand_AT
    
    add <- function(metric_code, scen, source, value) {
      rows[[length(rows) + 1L]] <<- tibble(
        dimension   = d,
        metric_code = metric_code,
        scenario    = scen,
        source      = source,
        value       = value
      )
    }
    
    add("species", "IUCN 100", "empirical", sp_emp_100)
    add("species", "IUCN AT",  "empirical", sp_emp_AT)
    add("species", "IUCN 100", "null",      sp_null_100)
    add("species", "IUCN AT",  "null",      sp_null_AT)
    
    add("fric", "IUCN 100", "empirical", fric_emp_100)
    add("fric", "IUCN AT",  "empirical", fric_emp_AT)
    add("fric", "IUCN 100", "null",      fric_null_100)
    add("fric", "IUCN AT",  "null",      fric_null_AT)
    
    add("fun", "IUCN 100", "empirical", fun_emp_100)
    add("fun", "IUCN AT",  "empirical", fun_emp_AT)
    add("fun", "IUCN 100", "null",      fun_null_100)
    add("fun", "IUCN AT",  "null",      fun_null_AT)
  }
  
  bind_rows(rows)
}

long_df <- build_long_df(extinction_results, n_sp_total)


# ============================================================================
# 3. Retrieve SES + p-values -------- -----------------------------------------
# ============================================================================
# SES was computed on the raw positive loss (loss_FRic_*, delta_FUn_*).
# For readability of the "Change in FRic" panel (where loss is plotted
# as negative), the FRic SES sign is flipped so that the visual direction
# (empirical boxplot below the null violin) corresponds to a
# with a negative SES. For FUn, original sign is kept.
build_ses_df <- function(extinction_results) {
  
  bind_rows(lapply(names(extinction_results), function(d) {
    s <- extinction_results[[d]]$ses_stats
    
    s$dimension   <- d
    s$metric_code <- ifelse(s$metric == "FRic loss",   "fric",
                            ifelse(s$metric == "FUn change",  "fun",
                                   NA_character_))
    
    s$SES_signed <- ifelse(s$metric_code == "fric", -s$SES, s$SES)
    
    s[, c("dimension", "scenario", "metric_code",
          "obs_mean", "null_mean", "null_sd",
          "SES", "SES_signed", "p_value", "alternative")]
  }))
}

ses_df <- build_ses_df(extinction_results)


# ============================================================================
# 4. Mise en forme des facteurs ----------------------------------------------
# ============================================================================
long_df <- long_df %>%
  mutate(
    dimension   = factor(dimension,
                         levels = PARAMS_FIG$dim_order,
                         labels = PARAMS_FIG$dim_labels),
    scenario    = factor(scenario, levels = PARAMS_FIG$scenario_order),
    metric_code = factor(metric_code, levels = PARAMS_FIG$metric_codes),
    x_num       = PARAMS_FIG$x_pos[as.character(scenario)]
  )

ses_df <- ses_df %>%
  mutate(
    dimension   = factor(dimension,
                         levels = PARAMS_FIG$dim_order,
                         labels = PARAMS_FIG$dim_labels),
    scenario    = factor(scenario, levels = PARAMS_FIG$scenario_order),
    metric_code = factor(metric_code, levels = PARAMS_FIG$metric_codes),
    x_num       = PARAMS_FIG$x_pos[as.character(scenario)]
  )


# ============================================================================
# 5. Build one panel (1 dimension x 1 metric, 2 scenarios) -------- --------
# ============================================================================
make_panel <- function(dim_lab, mc) {
  
  dim_col <- PARAMS_FIG$dim_colors[
    PARAMS_FIG$dim_order[match(dim_lab, PARAMS_FIG$dim_labels)]
  ]
  
  sub_emp  <- long_df %>%
    filter(dimension == dim_lab, metric_code == !!mc, source == "empirical")
  sub_null <- long_df %>%
    filter(dimension == dim_lab, metric_code == !!mc, source == "null")
  sub_ses  <- ses_df %>%
    filter(dimension == dim_lab, metric_code == !!mc)
  
  # Combined Y bounds
  yvals <- c(sub_emp$value, sub_null$value, 0)
  yvals <- yvals[is.finite(yvals)]
  if (length(yvals) == 0L) return(ggplot() + theme_void())
  yspan   <- diff(range(yvals))
  if (yspan == 0) yspan <- abs(mean(yvals)) * 0.1 + 1
  ylim_lo <- min(yvals) - 0.05 * yspan
  ylim_hi <- max(yvals) + 0.25 * yspan   # marge pour annotation
  
  p <- ggplot()
  
  # ---- Reference line at 0 ----
  p <- p + geom_hline(yintercept = 0, color = "grey75",
                      linewidth = 0.25, linetype = "dashed")
  
  # ---- NULL VIOLINS for both scenarios ----
  if (nrow(sub_null) > 0) {
    p <- p + geom_violin(
      data = sub_null,
      aes(x = x_num, y = value, group = scenario),
      fill = PARAMS_FIG$null_fill, color = PARAMS_FIG$null_border,
      width = 0.7, linewidth = 0.3, alpha = 0.85
    )
  }
  
  # ---- EMPIRICAL per scenario ----
  for (sc in PARAMS_FIG$scenario_order) {
    
    sub_e_sc <- sub_emp %>% filter(scenario == sc)
    if (nrow(sub_e_sc) == 0L) next
    
    x_sc <- PARAMS_FIG$x_pos[[sc]]
    
    is_deterministic <- (length(unique(round(sub_e_sc$value, 8))) == 1L)
    
    if (is_deterministic) {
      const_val <- unique(sub_e_sc$value)[1]
      p <- p + geom_segment(
        data = data.frame(x = x_sc - 0.32, xend = x_sc + 0.32,
                          y = const_val, yend = const_val),
        aes(x = x, xend = xend, y = y, yend = yend),
        color = dim_col, linewidth = 0.9,
        inherit.aes = FALSE
      )
    } else {
      p <- p + geom_boxplot(
        data = sub_e_sc,
        aes(x = x_num, y = value),
        fill = NA, color = dim_col,
        width = 0.28, linewidth = 0.4,
        outlier.size = 0.25, outlier.alpha = 0.3
      )
    }
    
    # ---- Annotation SES + p-value (sauf Species change) ----
    if (mc != "species" && nrow(sub_ses) > 0) {
      ses_sc <- sub_ses %>% filter(scenario == sc)
      if (nrow(ses_sc) == 1L && !is.na(ses_sc$SES_signed)) {
        ses_val <- ses_sc$SES_signed
        pv_val  <- ses_sc$p_value
        pv_str  <- if (is.na(pv_val))     "p = NA"
        else if (pv_val < 1e-3) "p < 0.001"
        else                    sprintf("p = %.3f", pv_val)
        annot_label <- sprintf("SES = %.2f\n%s", ses_val, pv_str)
        
        p <- p + annotate(
          "text",
          x = x_sc, y = ylim_hi - 0.02 * yspan,
          label = annot_label,
          size = PARAMS_FIG$pval_text_size, vjust = 1, fontface = "bold",
          color = "grey15", lineheight = 0.85
        )
      }
    }
  }
  
  # ---- X scale and theme ----
  p +
    scale_x_continuous(
      breaks = unname(PARAMS_FIG$x_pos),
      labels = names(PARAMS_FIG$x_pos),
      limits = c(0.4, 2.6),
      expand = c(0, 0)
    ) +
    coord_cartesian(ylim = c(ylim_lo, ylim_hi), clip = "off") +
    labs(x = NULL, y = NULL) +
    theme_minimal(base_size = PARAMS_FIG$base_font_size) +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor   = element_blank(),
      panel.grid.major.y = element_line(color = "grey92", linewidth = 0.25),
      panel.background   = element_rect(fill = "white", color = NA),
      plot.background    = element_rect(fill = "white", color = NA),
      panel.border       = element_rect(color = "grey60", fill = NA,
                                        linewidth = 0.3),
      axis.text.y        = element_text(size = PARAMS_FIG$base_font_size - 1.5,
                                        color = "grey20"),
      axis.text.x        = element_text(size = PARAMS_FIG$base_font_size - 1,
                                        color = "grey20"),
      axis.ticks.x       = element_line(color = "grey60", linewidth = 0.25),
      plot.margin        = margin(3, 4, 3, 4)
    )
}


# ============================================================================
# 6. Assemblage de la grille 3 x 3 -------------------------------------------
# ============================================================================
plot_list <- list()
panel_idx <- 0

# Parcours : ligne (metric_code) puis colonne (dimension)
for (m_code in PARAMS_FIG$metric_codes) {
  for (dim_lab in PARAMS_FIG$dim_labels[PARAMS_FIG$dim_order]) {
    
    panel_idx <- panel_idx + 1
    pp <- make_panel(dim_lab, m_code)
    
    is_top_row    <- (m_code == PARAMS_FIG$metric_codes[1])
    is_left_col   <- (dim_lab == PARAMS_FIG$dim_labels[PARAMS_FIG$dim_order][1])
    is_bottom_row <- (m_code == PARAMS_FIG$metric_codes[length(PARAMS_FIG$metric_codes)])
    
    # Column title (top), coloured by dimension
    if (is_top_row) {
      dim_key <- PARAMS_FIG$dim_order[match(dim_lab, PARAMS_FIG$dim_labels)]
      pp <- pp + ggtitle(dim_lab) +
        theme(plot.title = element_text(
          size  = PARAMS_FIG$base_font_size + 1,
          hjust = 0.5,
          face  = "bold",
          color = PARAMS_FIG$dim_colors[[dim_key]],
          margin = margin(b = 2)
        ))
    }
    
    # Label Y (colonne 1 uniquement)
    if (is_left_col) {
      pp <- pp + ylab(PARAMS_FIG$metric_labels[[m_code]]) +
        theme(axis.title.y = element_text(
          size   = PARAMS_FIG$base_font_size,
          face   = "bold",
          margin = margin(r = 4)
        ))
    }
    
    # Masquer les ticks X partout sauf sur la ligne du bas
    if (!is_bottom_row) {
      pp <- pp + theme(
        axis.text.x  = element_blank(),
        axis.ticks.x = element_blank()
      )
    }
    
    plot_list[[panel_idx]] <- pp
  }
}

final_fig <- patchwork::wrap_plots(plot_list, nrow = 3, ncol = 3, byrow = TRUE) 


# ============================================================================
# 7. Export -------------------------------------------------------------------
# ============================================================================
out_pdf <- file.path(PARAMS_FIG$out_dir, paste0(PARAMS_FIG$fig_basename, ".pdf"))
ggsave(out_pdf, final_fig,
       width = PARAMS_FIG$width_mm, height = PARAMS_FIG$height_mm,
       units = "mm", device = cairo_pdf)
